- label: "JIRA"
  message: "$issuePrefix"
  icon: "jira"
  color: "blue"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"



- label: "Preview"
  message: "PR-$prNumber"
  color: "blue"
  url: "https://pr-$prNumber.company.com"
